# Site settings
title: Robinson Center Saturday Enrichment Program
email: garofali@uw.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/robinson-center/" # the subpath of your site, e.g. /blog/
url: "http://kgarofali.github.io/robinson-center" # the base hostname & protocol for your site
premap_home: "https://robinsoncenter.uw.edu/"


# Build settings
markdown: kramdown
